### ISSUE TITLE
Mainpage | Необходимо уменьшить бекграунд со слайдером по высоте

### ISSUE THREAD

**Issue by yezzziam** [coderiver/tours4u#2]
На главной странице, необходимо уменьшить слайдер в 2 раза по высоте. 
![screenshot 2015-11-18 22 38 09](https://cloud.githubusercontent.com/assets/52105/11253580/2bd85eec-8e45-11e5-9c8b-379cebb06e35.png)

**Comment by valeraderevshukov** [comment]
что именно вы имеете ввиду под уменьшить background? здесь картинка взята из макета, она растянута по высоте и ширине блока, блок к которому она привязана пропорционально увеличивается и уменьшается относительно окна браузера соответственно фон (background) подстраивается под этот блок, уменьшить размер фона я не могу, разве что вы сбросите эту картинку в X2, то есть увеличенную в два раза, тогда я её заменю и фон будет казаться в 2 раза меньшым

**Comment by yezzziam** [comment]
Привет, идея в том, что когда такие большие отступы и высота бекграунда, то поля поиска не видно на средних разрешениях экрана у пользователей. Идея в этом, это косяк дизайнера, я бы хотел чтобы мы оставили бекграунд, чтобы он тянулся по ширине, но уменьшили его максимальную высоту до 650/700px, а мы уже с разработчиками будем кропать изображения так же и контент будут подгонять под это.
