### ISSUE TITLE
Search Preloader | Уменьшить бекграунд с названием страны на 30-40%

### ISSUE THREAD

**Issue by yezzziam** [coderiver/tours4u#5]
+ по возможности уменьшить отступы, чтобы сам прелоадер помещался по высоте в 700px
![screenshot 2015-11-19 00 11 48](https://cloud.githubusercontent.com/assets/52105/11255994/25ea152c-8e52-11e5-9592-6aa45bc98f33.png)

**Comment by valeraderevshukov** [comment]
готово
